config/routes.rb
Rails.application.routes.draw do
  root 'starts#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # comments create
  post '/posts/:post_id/comments/create'=> 'comments#create'

  # comments destroy
  post '/' => 'comments#destroy'

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new
    @comment.content = params[:content]
    @comment.post_id = params[:post_id]
    @comment.user = current_user
    @comment.save

    redirect_to "/posts/#{params[:post_id]}"
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy

    redirect_to "/posts/#{params[:post_id]}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index, :show ]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/starts_helper.rb
module StartsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>독후감</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- bootstrap 4 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    <!-- Bree Serif -->
    <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to '독후감', root_path, class: "navbar-brand", id: "site-title" %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to '글목록', posts_path, class: "nav-link option-title" %>
              </li>
              <li class="nav-item">
                <%= link_to '내정보', edit_user_registration_path, class: "nav-link option-title" %>
              </li>
              <li class="nav-item">
                <%= link_to '로그아웃', destroy_user_session_path, method: :delete, data: { confirm: "로그아웃 하시겠습니까?" }, class: "nav-link option-title" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to '글목록', posts_path, class: "nav-link option-title" %>
              </li>
              <li class="nav-item">
                <%= link_to "페이스북으로 로그인하기", user_facebook_omniauth_authorize_path, class: "nav-link option-title" %>
              </li>
              <li class="nav-item">
                <%= link_to '가입하기', new_user_registration_path, class: "nav-link option-title" %>
              </li>
              <li class="nav-item">
                <%= link_to '로그인', new_user_session_path, class: "nav-link option-title" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container yield">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field row" id="form-title">
    <%= f.label "제목", class: "col-md-1" %>
    <%= f.text_field :title, class: "col review_form" %>
  </div>

  <div class="field row" id="form-content">
    <%= f.label "내용", class: "col-md-1" %>
    <%= f.text_area :content, class: "col review_form" %>
  </div>

  <div class="row check_form">
    <div class="actions ml-auto">
      <%= image_submit_tag("check.png", id: "check_button")%>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="category">
  게시글 목록
</p>

<hr>

<% @posts.each do |post| %>
  <div class="row">
    <p class="col-md-1 catalogue catalogue-title">
      <%= post.id %>
    </p>
    <p class="col catalogue">
      <%= link_to post.title, post, class: "col" %>
    </p>
  </div>
  <hr>
<% end %>

<br>

<div class="container row">
  <%= link_to '새 리뷰 작성하기', new_post_path, style: "margin-top:5px;" %>
</div>

app/views/posts/new.html.erb
<p id="description">
  게시글 작성 <br>
</p>

<hr>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="category">
    <%= @post.title %>
</p>

<hr>

<p>
  <%= @post.content %>
</p>

<div class="row">
  <div class="ml-auto">
    <%= link_to '수정', edit_post_path(@post) %>
    <%= link_to '목록', posts_path %>
    <%= link_to '삭제', @post, method: :delete, data: { confirm: '삭제하면 모든 데이터가 지워집니다. 정말 삭제하시겠습니까?' } %>
  </div>
</div>

<form action="/posts/<%=@post.id%>/comments/create" method="post">
  <label for="content">
    <input type="text" name="content">
  </label>
  <input type="submit">
</form>

<% @comments.each do |comment| %>
  <p><%= comment.content %></p>
<% end %>

app/views/starts/index.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="row">
      <%= link_to '내정보', edit_user_registration_path, class: "nav-link col" %>
      <%= link_to '로그아웃', destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }, class: "nav-link col" %>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row">
      <%= link_to "페이스북으로 로그인하기", user_facebook_omniauth_authorize_path, class: "nav-link col"  %>
      <%= link_to '가입하기', new_user_registration_path, class: "nav-link col" %>
      <%= link_to '로그인', new_user_session_path, class: "nav-link col" %>
    </div>
  </div>
<% end %>